#!/usr/bin/env bash

# echo I am the c++ bash wrapper script with args: $@

case "$1" in
    build)
        if [ ! -f json.hpp ]; then
            wget https://github.com/nlohmann/json/releases/download/v3.11.2/json.hpp
        fi
        meson build
        cd build
        ninja
        ;;
    *)
        cd build
        ./test-cpp $@
        ;;
esac
