#pragma once
// 
// https://github.com/AlexanderZvyagin/dto-code-generator
// Generated by CODE GENERATOR OF DATA TRANSFER OBJECTS (cgdto) version 0.6.4
// 
// Generated from schema: MonteCarlo SDK version (0.2.1)
// 


#include <optional>
#include <string>
#include <vector>
#include <map>
#include <stdexcept>
#include <cmath>

#include <nlohmann/json.hpp>
using json = nlohmann::json;


#include "Updater.hpp"
namespace dto {
class BrownianMotion;
std::string BrownianMotion_to_json_string(const BrownianMotion &obj);
class BrownianMotion: public Updater {
public:


    
    BrownianMotion (
        float start = NAN,
        float drift = NAN,
        float diffusion = NAN,
        std::string title = ""
    )
    : Updater (
        "BrownianMotion",
        {},
        {drift,diffusion},
        start,
        title
    )
    {
    }

    bool operator == (const BrownianMotion &other) const {
        if (Updater::operator != (other)) return false;
        return true;
    }
    bool operator != (const BrownianMotion &other) const {return not(*this==other);}
    std::string json (void) const {
        return BrownianMotion_to_json_string(*this);
    }
}; // BrownianMotion
inline
void to_json(json &j, const BrownianMotion &obj) try {
    j = json::object();
    to_json(j,static_cast<const Updater &>(obj));
} catch (const std::exception &e) {
    std::throw_with_nested(std::runtime_error("void to_json(json &j, const BrownianMotion &obj) exception"));
}

inline
std::string BrownianMotion_to_json_string(const BrownianMotion &obj) {
    json j;
    to_json(j,obj);
    return j.dump();
}
inline
void from_json(const json &j, BrownianMotion &obj) try {
    from_json(j,static_cast<Updater &>(obj));
} catch (const std::exception &e) {
    std::throw_with_nested(std::runtime_error("void from_json(const json &j, BrownianMotion &obj) exception"));
}
inline
BrownianMotion BrownianMotion_from_json(const json &j) {
    BrownianMotion obj;
    from_json(j,obj);
    return obj;
}
} // namespace dto

