#pragma once
// 
// https://gitlab.com/zvyagin.alexander/dto-code-generator
// Generated by CODE GENERATOR OF DATA TRANSFER OBJECTS (cgdto) version 0.4.1
// 
//         Generated from: MonteCarlo SDK version (0.2.0)
//         


#include <optional>
#include <string>
#include <vector>
#include <map>
#include <stdexcept>
#include <cmath>

#include <nlohmann/json.hpp>
using json = nlohmann::json;


#include "Updater.hpp"
namespace dto {
class BrownianMotionRef;
std::string BrownianMotionRef_to_json_string(const BrownianMotionRef &obj);
class BrownianMotionRef: public Updater {
public:


    
    BrownianMotionRef (
        float start = NAN,
        int drift = -88,
        int diffusion = -88,
        std::string title = ""
    )
    : Updater (
        "BrownianMotion",
        {drift,diffusion},
        {},
        start,
        title
    )
    {
    }

    bool operator == (const BrownianMotionRef &other) const {
        if (Updater::operator != (other)) return false;
        return true;
    }
    bool operator != (const BrownianMotionRef &other) const {return not(*this==other);}
    std::string json (void) const {
        return BrownianMotionRef_to_json_string(*this);
    }
};
inline
void to_json(json &j, const BrownianMotionRef &obj) {
    j = json::object();
    to_json(j,static_cast<const Updater &>(obj));
}

inline
std::string BrownianMotionRef_to_json_string(const BrownianMotionRef &obj) {
    json j;
    to_json(j,obj);
    return j.dump();
}
inline
void from_json(const json &j, BrownianMotionRef &obj) {
    from_json(j,static_cast<Updater &>(obj));
}
inline
BrownianMotionRef BrownianMotionRef_from_json(const json &j) {
    BrownianMotionRef obj;
    from_json(j,obj);
    return obj;
}
} // namespace dto

