#pragma once
// 
// https://gitlab.com/zvyagin.alexander/dto-code-generator
// Generated by CODE GENERATOR OF DATA TRANSFER OBJECTS (cgdto) version 0.4.0
// 
//         Generated from: MonteCarlo SDK version (0.2.0)
//         


#include <optional>
#include <string>
#include <vector>
#include <map>
#include <stdexcept>
#include <cmath>

#include "json.hpp"
using json = nlohmann::json;


class DtoError;
std::string DtoError_to_json_string(const DtoError &obj);
class DtoError {
public:

    std::optional<std::string> message;
    std::optional<std::string> details;
    std::optional<int> code;
    std::optional<std::vector<DtoError>> errors;

    
    DtoError (
        std::optional<std::string> message = {},
        std::optional<std::string> details = {},
        std::optional<int> code = {},
        std::optional<std::vector<DtoError>> errors = {}
    )
    : message (
        message
    )
    , details (
        details
    )
    , code (
        code
    )
    , errors (
        errors
    )
    {
    }

    bool operator == (const DtoError &other) const {
        if (message != other.message) return false;
        if (details != other.details) return false;
        if (code != other.code) return false;
        if (errors != other.errors) return false;
        return true;
    }
    bool operator != (const DtoError &other) const {return not(*this==other);}
    std::string json (void) const {
        return DtoError_to_json_string(*this);
    }
};
inline
void to_json(json &j, const DtoError &obj) {
    j = json::object();
    if(obj.message.has_value())
        j["message"] = obj.message.value();
    if(obj.details.has_value())
        j["details"] = obj.details.value();
    if(obj.code.has_value())
        j["code"] = obj.code.value();
    if(obj.errors.has_value())
        j["errors"] = obj.errors.value();
}

inline
std::string DtoError_to_json_string(const DtoError &obj) {
    json j;
    to_json(j,obj);
    return j.dump();
}
inline
void from_json(const json &j, DtoError &obj) {
    if(auto it=j.find("message"); it!=j.end() and !it->is_null())
        obj.message = *it;
    if(auto it=j.find("details"); it!=j.end() and !it->is_null())
        obj.details = *it;
    if(auto it=j.find("code"); it!=j.end() and !it->is_null())
        obj.code = *it;
    if(auto it=j.find("errors"); it!=j.end() and !it->is_null())
        obj.errors = *it;
}
inline
DtoError DtoError_from_json(const json &j) {
    DtoError obj;
    from_json(j,obj);
    return obj;
}

