#pragma once
// 
// https://github.com/AlexanderZvyagin/dto-code-generator
// Generated by CODE GENERATOR OF DATA TRANSFER OBJECTS (cgdto) version 0.6.2
// 
// Generated from schema: MonteCarlo SDK version (0.2.0)
// 


#include <optional>
#include <string>
#include <vector>
#include <map>
#include <stdexcept>
#include <cmath>

#include <nlohmann/json.hpp>
using json = nlohmann::json;


#include "Updater.hpp"
namespace dto {
class Multiplication;
std::string Multiplication_to_json_string(const Multiplication &obj);
class Multiplication: public Updater {
public:


    
    Multiplication (
        std::vector<int> refs = {},
        float factor = 1,
        std::string title = ""
    )
    : Updater (
        "Multiplication",
        refs,
        {factor},
        0,
        title
    )
    {
    }

    bool operator == (const Multiplication &other) const {
        if (Updater::operator != (other)) return false;
        return true;
    }
    bool operator != (const Multiplication &other) const {return not(*this==other);}
    std::string json (void) const {
        return Multiplication_to_json_string(*this);
    }
}; // Multiplication
inline
void to_json(json &j, const Multiplication &obj) try {
    j = json::object();
    to_json(j,static_cast<const Updater &>(obj));
} catch (const std::exception &e) {
    std::throw_with_nested(std::runtime_error("void to_json(json &j, const Multiplication &obj) exception"));
}

inline
std::string Multiplication_to_json_string(const Multiplication &obj) {
    json j;
    to_json(j,obj);
    return j.dump();
}
inline
void from_json(const json &j, Multiplication &obj) try {
    from_json(j,static_cast<Updater &>(obj));
} catch (const std::exception &e) {
    std::throw_with_nested(std::runtime_error("void from_json(const json &j, Multiplication &obj) exception"));
}
inline
Multiplication Multiplication_from_json(const json &j) {
    Multiplication obj;
    from_json(j,obj);
    return obj;
}
} // namespace dto

