#pragma once
// 
// https://gitlab.com/zvyagin.alexander/dto-code-generator
// Generated by CODE GENERATOR OF DATA TRANSFER OBJECTS (cgdto) version 0.4.0
// 
//         Generated from: MonteCarlo SDK version (0.2.0)
//         


#include <optional>
#include <string>
#include <vector>
#include <map>
#include <stdexcept>
#include <cmath>

#include "json.hpp"
using json = nlohmann::json;


#include "Updater.hpp"
class Multiplication;
std::string Multiplication_to_json_string(const Multiplication &obj);
class Multiplication: public Updater {
public:


    
    Multiplication (
        std::vector<int> refs = {},
        float factor = 1,
        std::string title = ""
    )
    : Updater (
        "Multiplication",
        refs,
        {factor},
        0,
        title
    )
    {
    }

    bool operator == (const Multiplication &other) const {
        if (Updater::operator != (other)) return false;
        return true;
    }
    bool operator != (const Multiplication &other) const {return not(*this==other);}
    std::string json (void) const {
        return Multiplication_to_json_string(*this);
    }
};
inline
void to_json(json &j, const Multiplication &obj) {
    j = json::object();
    to_json(j,static_cast<const Updater &>(obj));
}

inline
std::string Multiplication_to_json_string(const Multiplication &obj) {
    json j;
    to_json(j,obj);
    return j.dump();
}
inline
void from_json(const json &j, Multiplication &obj) {
    from_json(j,static_cast<Updater &>(obj));
}
inline
Multiplication Multiplication_from_json(const json &j) {
    Multiplication obj;
    from_json(j,obj);
    return obj;
}

