#pragma once
// 
// https://github.com/AlexanderZvyagin/dto-code-generator
// Generated by CODE GENERATOR OF DATA TRANSFER OBJECTS (cgdto) version 0.7.1
// 
// Generated from schema: MonteCarlo SDK version (0.5.0)
// 


#include <optional>
#include <string>
#include <vector>
#include <map>
#include <stdexcept>
#include <cmath>

#include <nlohmann/json.hpp>
using json = nlohmann::json;


#include "Updater.hpp"
namespace dto {
class Polynom;
std::string Polynom_to_json_string(const Polynom &obj);
class Polynom: public Updater {
public:


    
    Polynom (
        int ref = -1,
        std::vector<float> args = {},
        std::string title = ""
    )
    : Updater (
        "Polynom",
        {ref},
        args,
        {},
        title
    )
    {
    }

    bool operator == (const Polynom &other) const {
        if (Updater::operator != (other)) return false;
        return true;
    }
    bool operator != (const Polynom &other) const {return not(*this==other);}
    std::string json (void) const {
        return Polynom_to_json_string(*this);
    }
}; // Polynom
inline
void to_json(json &j, const Polynom &obj) try {
    j = json::object();
    to_json(j,static_cast<const Updater &>(obj));
} catch (const std::exception &e) {
    std::throw_with_nested(std::runtime_error("void to_json(json &j, const Polynom &obj) exception"));
}

inline
std::string Polynom_to_json_string(const Polynom &obj) {
    json j;
    to_json(j,obj);
    return j.dump();
}
inline
void from_json(const json &j, Polynom &obj) try {
    from_json(j,static_cast<Updater &>(obj));
} catch (const std::exception &e) {
    std::throw_with_nested(std::runtime_error("void from_json(const json &j, Polynom &obj) exception"));
}
inline
Polynom Polynom_from_json(const json &j) {
    Polynom obj;
    from_json(j,obj);
    return obj;
}
} // namespace dto

