#pragma once
// 
// https://github.com/AlexanderZvyagin/dto-code-generator
// Generated by CODE GENERATOR OF DATA TRANSFER OBJECTS (cgdto) version 0.7.0
// 
// Generated from schema: MonteCarlo SDK version (0.2.1)
// 


#include <optional>
#include <string>
#include <vector>
#include <map>
#include <stdexcept>
#include <cmath>

#include <nlohmann/json.hpp>
using json = nlohmann::json;


#include "Updater.hpp"
namespace dto {
class SumAtPoints;
std::string SumAtPoints_to_json_string(const SumAtPoints &obj);
class SumAtPoints: public Updater {
public:


    
    SumAtPoints (
        int underlying = -88,
        std::vector<float> t = {},
        std::string title = ""
    )
    : Updater (
        "SumAtPoints",
        {underlying},
        t,
        0,
        title
    )
    {
    }

    bool operator == (const SumAtPoints &other) const {
        if (Updater::operator != (other)) return false;
        return true;
    }
    bool operator != (const SumAtPoints &other) const {return not(*this==other);}
    std::string json (void) const {
        return SumAtPoints_to_json_string(*this);
    }
}; // SumAtPoints
inline
void to_json(json &j, const SumAtPoints &obj) try {
    j = json::object();
    to_json(j,static_cast<const Updater &>(obj));
} catch (const std::exception &e) {
    std::throw_with_nested(std::runtime_error("void to_json(json &j, const SumAtPoints &obj) exception"));
}

inline
std::string SumAtPoints_to_json_string(const SumAtPoints &obj) {
    json j;
    to_json(j,obj);
    return j.dump();
}
inline
void from_json(const json &j, SumAtPoints &obj) try {
    from_json(j,static_cast<Updater &>(obj));
} catch (const std::exception &e) {
    std::throw_with_nested(std::runtime_error("void from_json(const json &j, SumAtPoints &obj) exception"));
}
inline
SumAtPoints SumAtPoints_from_json(const json &j) {
    SumAtPoints obj;
    from_json(j,obj);
    return obj;
}
} // namespace dto

