#!/usr/bin/env python3

from dto  import *
from mcsdk_test import *

if __name__ == '__main__':
    test_round_trip_python(
        sys.argv[1],
        sys.argv[2],
        sys.argv[3],
        sys.argv[4] if len(sys.argv)>4 else ''
    )
