#!/usr/bin/env bash

# echo I am the c++ bash wrapper script with args: $@

case "$1" in
    build)
        cd build
        ninja
        ;;
    *)
        cd build
        ./run-cpp $@
        ;;
esac
