#!/usr/bin/env bash

case "$1" in
    build)
        cp ../../output/dto.ts .
        cp ../../output/dto_tests.ts .
        npm install typescript
        ./node_modules/typescript/bin/tsc dto_tests.ts
        ;;
    *)
        node dto_tests.js $@
        ;;
esac
